### ISSUE TITLE
Can't retrieve instances and untaint nodes

### ISSUE THREAD

**Issue by Sryther** [outscale-dev/cloud-provider-osc#51]
**What happened**:

The osc-cloud-controller-manager DaemonSet is unable to retrieve instances metadata and can't request `GET ec2metadata/GetToken`.

```
2021/10/07 09:55:33 DEBUG: Request ec2metadata/GetToken Details:
---[ REQUEST POST-SIGN ]-----------------------------
PUT /latest/api/token HTTP/1.1
Host: 169.254.169.254
User-Agent: aws-sdk-go/1.28.2 (go1.15.6; linux; amd64)
Content-Length: 0
X-Aws-Ec2-Metadata-Token-Ttl-Seconds: 21600
Accept-Encoding: gzip

-----------------------------------------------------
2021/10/07 09:55:33 DEBUG: Response ec2metadata/GetToken Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 404 Not Found
Content-Length: 9
Connection: keep-alive
Content-Type: text/plain
Date: Thu, 07 Oct 2021 09:55:33 GMT
Server: nginx/1.12.2

-----------------------------------------------------
2021/10/07 09:55:33 Not Found
```

Note that the ec2metadata/GetMetadata works as expected (returns instance id).

On manager nodes, the osc-cloud-controller-manager pod says the instance (vm) is not found:

```
failed to initialize node XXX at cloudprovider: instance not found
```

**What you expected to happen**:

Remove the taint `node.cloudprovier.kubernetes.io/uninitialized=True:NoSchedule` on nodes.

**How to reproduce it (as minimally and precisely as possible)**:

From a clean install with Kubespray and the kubelet configured with --cloud-provider=external.

The VMs are tagged with `OscK8sClusterID/XXX` (I have a real value for XXX) and `OscK8sNodeName` with the same value as the label `kubernetes.io/hostname`.

Note the annotation `csi.volume.kubernetes.io/nodeid` is `{"ebs.csi.aws.com": "i-xxxxxxxx"}`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 19.9
- Cloud provider or hardware configuration: outscale
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): `Linux REDACTED 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubespray
- Others: -

/kind bug

**Comment by aniszosc** [comment]
Thank you for your feedback
> Maybe this information could be mentioned in the main README 🙂
I will add this detail in the README.

**Comment by Sryther** [comment]
Thanks for your answers. I close the issue since it's all resolved for me and all the necessary information are provided in here.
