### ISSUE TITLE
Unable to generate a certificate using LB FQDN with Letsencrypt

### ISSUE THREAD

**Issue by Ripolin** [outscale-dev/cloud-provider-osc#7]
**What would you like to be added**:

Update LB name generator to create smaller ones. Currently, CCM generate a LB name with 32 chars and Outscale append to it a random number, region name and domain name. Finally LB FQDN have a length > 64 chars and Letsencrypt refuse to generate a certificate for it (https://community.letsencrypt.org/t/a-certificate-for-a-63-character-domain/78870).

For example, for a LB name like 1148b643e5454a23964c26d7ca421bc, FQDN is a1148b643e5454a23964c26d7ca421bc-013845137.eu-west-2.lbu.outscale.com.

**Why is this needed**:

To allow Letsencrypt generate certificates using LB FQDN

/kind feature

**Comment by aniszosc** [comment]
Hello,
Actually the LB name is the K8S Service object field ".metadata.uid" without "-" (dash) character and truncated to 32 characters(max length of an LB NAME).
To answer your request we will make the lb generation more flexible and customisable by controlling the lb name length.
we will provide a solution asap.
